### ISSUE TITLE
Failed to scan files

### ISSUE THREAD

**Issue by nulltoken** [VerifyTests/DiffEngine#542]
* DiffEngineTray Version: 15.5.1+1cbcffbaa5645ca7e930d8bfbb084e8b3f37fd7e
 * OS: Microsoft Windows NT 10.0.19045.0
 * Action: Failed to scan files
 * Exception:
```
System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.ProcessManager.OpenProcess(Int32 processId, Int32 access, Boolean throwIfExited)
   at System.Diagnostics.NtProcessManager.GetModules(Int32 processId, Boolean firstModuleOnly)
   at System.Diagnostics.NtProcessManager.GetFirstModule(Int32 processId)
   at ProcessEx.KillAndDispose(Process process) in C:\projects\diffengine\src\DiffEngineTray\ProcessEx.cs:line 51
   at Tracker.KillProcesses(TrackedMove move) in C:\projects\diffengine\src\DiffEngineTray\Tracker.cs:line 284
   at Tracker.<HandleScanMove>g__RemoveAndKill|8_0(TrackedMove tacked) in C:\projects\diffengine\src\DiffEngineTray\Tracker.cs:line 48
   at Tracker.HandleScanMove(KeyValuePair`2 pair) in C:\projects\diffengine\src\DiffEngineTray\Tracker.cs:line 55
   at AsyncTimer.RunLoop(CancellationToken cancel) in C:\projects\diffengine\src\DiffEngineTray\AsyncTimer.cs:line 32
```

Hey @SimonCropp ! :wave:

I discovered the popup by closing some windows. I followed the directions and opened an issue.
But honestly, I have no idea when it happened, nor any hint regarding how to repro it.

Feel free to close if it's not usable enough.

**Comment by SimonCropp** [comment]
thanks. yeah that a valid bug. that exception should be swallowed. will fix shortly
